### ISSUE TITLE
Errors and warnings in Dev-Tools when using Dailymotion

### ISSUE THREAD

**Issue by abvas** [luwes/playerx#37]
When using provider = deilymotion, I get a lot of warnings and errors in Dev-Tools.

![Image 26](https://user-images.githubusercontent.com/47285364/148663410-88091348-f8c2-4295-90e8-dc48d596e460.png)

I get this in my application, and I also see it on the demo page (for example: https://www.dailymotion.com/ video / x85qs0t)

What could be the cause of these errors and warnings? And how can this be reduced?

windows 10,
chrome - 97.0.4692.71,
playerx - 0.9.0,
ad blockers are disabled.

Thank you.

**Comment by luwes** [comment]
@abvas the issue seems to be that the embeds can not be found (see 404). 
These might be Dailymotion videos that are not publicly available?
https://faq.dailymotion.com/hc/en-us/articles/115009030028-Content-visibility

I tried loading https://dev.playerx.io/demo/dailymotion/ on Windows 10, Chrome 97 (Browserstack) and it seemed to work fine
